#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true
apt:
  preserve_sources_list: true

users:
  - default
  - name: maxx
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC63ek2uUd3x4ahSCM3p6NpSTKusfaUwpCVfDATLLvvqAJ9KPZTMUSL1sm+F/Fr3JqSI7eXvqUMn7TdDx/G4YG5ZJSJXOs/LIozw7lPMX3HhwDeYdjbzPPcTDKnu9ozDB6gPvvBAHRRMr7MGtvY8XqrNA+LPndOe7rCqzH5JKzEtc/MG+XycfXQUKef0ePkLe/Wb6O/EGmfPe3ZxBkObZNu5J2EMZPBxMy7G0YAun8KFoNf8ZiaKhibk0d6doje9kV9OA/8e84icDu840UkObJjxIofWB+zpRhd4iJVuGGUXUBGNzej+qAYGUt8b3ip2Sa8sgCQR6sJP5dwYuStLp3JLDk2fB6niE5SjyePXhdszPSm3AGSWjw6y4uYhMJRc672Nw0Lc2GImMvUvVn+lOFV/zRMAOnWYsnYMULDwPWXyLv+hz4gdzqTWULPr3woZq3hsYL1NjLB99Zk4arsuKxnb+jaztAfRx2PoNbqbIhqsLHfGMzD6AqVsz29W4S01iU= user@MacBookAir"

runcmd:
  #ruby
  - sudo apt update
  - sudo apt install -y ruby-full ruby-bundler build-essential


  #mongo
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sudo systemctl start mongod
  - sudo systemctl enable mongod

  #deploy
  - sudo apt-get install -y git
  - cd /home/maxx
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit
  - bundle install
  - puma -d